
#ifndef ENUM_TOKEN_H
# define ENUM_TOKEN_H

typedef enum
{
	// First level token
	TOKEN_UNCLASSIFIED = -1,
	TOKEN_NULL = 0,
	TOKEN_BLANK,
	TOKEN_PIPE = 10,
	TOKEN_INPUT_CHEVRON = 31,
	TOKEN_OUTPUT_CHEVRON = 32,
	TOKEN_APPEND_CHEVRON = 33,
	TOKEN_HERE_DOC = 40,
	// Second level token
	TOKEN_COMMAND = 100,
	TOKEN_FILE = 200,
	TOKEN_HD_ARG = 400,
	// Third level token
	TOKEN_ARGUMENT = 1000,
	TOKEN_BUILT_IN = 1001,
	TOKEN_BINARY = 1002,
	TOKEN_HD_DELIM = 4002,
	/*
	TOKEN_WORD,
	TOKEN_SINGLE_QUOTE,
	TOKEN_DOUBLE_QUOTE,
	TOKEN_PARANTHESIS,
	TOKEN_AND,
	TOKEN_OR,
	TOKEN_WILDCARD,
	TOKEN_BOOLEAN,
	TOKEN_LIMITER,
	TOKEN_STRING,
	TOKEN_NOT_FINISH,
	TOKEN_FLAGS,
	TOKEN_ARGUMENT
	TOKEN_VARIABLE,
	*/
} TokenType;

#endif



