
#ifndef ENUM_TOKEN_H
# define ENUM_TOKEN_H

typedef enum
{
	//unclassified
	TOKEN_UNCLASSIFIED = -1,
	//Other token
	TOKEN_NULL = 0,
	TOKEN_BLANK,
	//Redirection
	TOKEN_REDIRECTION = 10,
	TOKEN_PIPE,
	TOKEN_INPUT_CHEVRON,
	TOKEN_OUTPUT_CHEVRON,
	TOKEN_APPEND_CHEVRON,
	TOKEN_HERE_DOC,
	//Word
	TOKEN_WORD = 20,
	TOKEN_SINGLE_QUOTE,
	TOKEN_DOUBLE_QUOTE,
	TOKEN_PARANTHESIS,
	//File
	TOKEN_FILE = 30,
	TOKEN_AND,
	TOKEN_OR,
	TOKEN_WILDCARD,
	TOKEN_BOOLEAN,
	TOKEN_LIMITER,
	TOKEN_STRING,
	TOKEN_NOT_FINISH,
	//Built-in / Binary
	TOKEN_COMMAND = 40,
	TOKEN_BUILT_IN,
	TOKEN_BINARY,
	TOKEN_FLAGS,
	//Arg
	TOKEN_ARGUMENT = 50,
	TOKEN_VARIABLE,
} TokenType;

#endif



